language: python
python:
  - "3.6"      #Default Python version on Travis CI

# The commands to install the dependencies
install:
  - sudo apt-get install php
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
  - coverage run TheUnitTests.py
  - pytest TheEndToEndTests.py

after_success:
  - coveralls
